import './globals.sass'

import { fontBody } from "@/data/fonts"
import Footer from "@/sections/Footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={fontBody.className}>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
