import './globals.sass'

import { fontBody } from "@/data/fonts"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={fontBody.className}>{children}</body>
    </html>
  )
}
