import './globals.sass'

import Footer from "@/sections/Footer"
import Header from "@/sections/Header"

import { fontBody } from "@/data/fonts"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={fontBody.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
